### ISSUE TITLE
Hello！xmind文件导入失败

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [Humorloos/SMR#1]
```
导入失败。
Traceback (most recent call last):
  File "aqt/importing.py", line 339, in importFile
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/61346236/xminder.py", line 46, in run
    selectedSheets = self.get_x_sheets()
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/61346236/xminder.py", line 93, in get_x_sheets
    selector = SingleSheetSelector(imp_sheets, doc_title)
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/61346236/sheetselectors.py", line 56, in __init__
    super().__init__(sheets, topic)
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/61346236/sheetselectors.py", line 29, in __init__
    self.build()
  File "/Users/xiamu/Library/Application Support/Anki2/addons21/61346236/sheetselectors.py", line 62, in build
    title = self.sheets[0]['sheet'].getTitle()
TypeError: 'NoneType' object is not callable
```
非常感谢您花时间开发这么棒的插件，我很需要它，但是无法导入

**Comment by Humorloos** [comment]
你可以进口例子地图吗？我的汉语还不太好。你也说英语吗？
Try to use the sample map for importing. If that works it has to be something about your concept map. Can you send me your xmind file? I can only fix this bug if I can reproduce your error.
You can download the sample map from here:
[https://github.com/Humorloos/SMR/blob/master/resources/example%20map.xmind](example map)

**Comment by CoffeeDrinkRabbit** [comment]
Thank you for your reply！ I can use English.

I found that after I changed the mapping style of your template, your template will also have import errors. 

I went back to your documentation and found that it was I who missed a specific mapping style before I could be correctly recognized by your add-on. But I don't know how to apply the style of your map to my own map. 

Xmind8 seems to provide the function of style export and import, but this function can only be used by users of Pro version. I haven't found the setting of copy paste style shortcut key that said in your instruction.

**Comment by Humorloos** [comment]
I know, importing designs unfortunately requires a xmind pro. However, you can still change key bindings in the basic version by using _preferences -> Keys -> Paste Style_ 

Actually the design itself does not matter for the imports to work. Using a different styles for concepts and relationships only helps to differentiate them. I just tried to reproduce your error by changing the design of the example map to the "Business 1" Default Design and the import still works. Is this what you meant by "changed the mapping style"?

Yes, the map has to be constructed as a concept map. That is, concepts contain answers to your cards and relationships contain the questions. The wikipedia article explains concept maps quite nicely.
https://zh.wikipedia.org/wiki/%E6%A6%82%E5%BF%B5%E5%9B%BE

For example, in the example map you can see that the concepts "information transfer and processing" and "neurotransmitters" are connected by a relationship with the title "requires". You have to build your whole concept map in this fashion for the imports to work correctly.

**Comment by CoffeeDrinkRabbit** [comment]
Make some changes based on your example, and then they can't be imported，I'm still trying to figure out what's going on.

**Comment by Humorloos** [comment]
how about you send me your map and i can check out what's wrong with it?

**Comment by CoffeeDrinkRabbit** [comment]
Sorry, I don't know how to use GitHub to upload files. Let me share them with Dropbox：https://www.dropbox.com/s/0o6i3bnxcvzv4k6/my%20sample.xmind.zip?dl=0

**Comment by Humorloos** [comment]
found out what the bug was caused by. I updated the addon and now you should be able to import the map that you sent me

**Comment by CoffeeDrinkRabbit** [comment]
That is great! Now it's working！！believe your add on can really help me in my topic speech of moral origin of anthropology next week.

Anki's review mechanism is really fragmented , but your add-on has made a blueprint possible for knowledge review, which is really important to me! Thank you！

**Comment by Humorloos** [comment]
你喜欢我的插件我很高兴！If there is anything else, feel free to contact me any time!
