### ISSUE TITLE
Confused about the use of One question after Multiple answers in the instructions

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [Humorloos/SMR#2]
Am I neglect some inconvenient cases or situations, in which it would be more appropriate to follow the instructions in these special situations?

I may prefer to use this way for the map sample：

biological psychology
investigates: information transfer and processing
modulated by: enzymes
example: MAO

> splits up: biogenic amines
> include: (1-4 / 4)
> Serotonin
> dopamine
> adrenaline
> noradrenaline

It took some time to figure out the logic of your Add-on reading the map, but after I figured it out, I felt that I gained a lot. Now I can understand the use of the bridge. If I didn't get it wrong, it's equivalent to suspending a question/topic/category after a concept and jumping directly to a sub level concept, right?

When there are not enough sub level materials under a concept, I often  find it difficult to detect the commonness between materials because of the lack of sufficient connection between them, so as to establish a category for them, or a proper question of connecting related materials . In this case, , the suspension of the question  becomes the best choice, that is, as for me , to directly organize and analyze the sub materials . So I can understand this usage.

But I'm also curious about the other usage that bothers me, because I usually deal with this situation in the way above. I guess there is something I have never met before, so I have no corresponding thinking. I look forward to the answer. Thanks again!

**Comment by CoffeeDrinkRabbit** [comment]
I think I've figured out that if I want to summarize multiple answers and continue to extend the following related concepts in the concept of summary, then this usage can more restore the thinking at that time, such as the situation that I need to conduct in-depth research or further enrich the knowledge map of a subject.

**Comment by CoffeeDrinkRabbit** [comment]
If I want to review the previous research path, I always browse and search from the parent node to the child node when I review the map.

 If I summarize a concept from multiple answers in a certain study and put the concept ahead of these answers, I may lose the research path at that time in the subsequent review, because I may browse in order later I mistakenly thought that I found the concept of summary first at that time, and then organized the sub nodes according to the concept.

This may mislead the follow-up research.

**Comment by CoffeeDrinkRabbit** [comment]
Thank you very much. I'm going to turn the issue off.

**Comment by Humorloos** [comment]
The way questions following multiple answers is implemented right now is very confusing and originates from way before I had written this addon.
As soon as I get to, I will improve this by making something like this importable:
![image](https://user-images.githubusercontent.com/53444879/70643217-e7c2a800-1c40-11ea-82a9-658b6cb423b4.png)
However, right now i'm not sure when I will get to do this.
Are there any issues left does this explain everything for you?
If you have suggestions on improvements you're always welcome to bring them up!

**Comment by CoffeeDrinkRabbit** [comment]
Oh yes! When I understand the mechanism, I understand it according to the function of XMIND, but I'm glad to understand when it's necessary to use the summary function in certain cases. 

If the situation is changed to the previous one, I won't think about it at all. Your instruction document gives me this opportunity. It's an important stimulus compared with the function of your plug-in Improvement ，which is more important to me.

I don't know programming and the summary function of XMIND doesn't seem to me to be easy to solve.

The good news is that your add-on now seems to meet my needs for the time being.Anyway I will keep up with this project ! look forward to your improvement.
