### ISSUE TITLE
A problem synchronizing on another device

### ISSUE THREAD

**Issue by CoffeeDrinkRabbit** [Humorloos/SMR#4]
I synchronized on another device without the corresponding Xmind files, and anki reported an error.

Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\webview.py", line 27, in cmd
  File "aqt\webview.py", line 87, in _onCmd
  File "aqt\webview.py", line 368, in _onBridgeCmd
  File "aqt\toolbar.py", line 56, in _linkHandler
  File "aqt\toolbar.py", line 80, in _syncLinkHandler
  File "C:\Users\10971\AppData\Roaming\Anki2\addons21\61346236\exportsync.py", line 196, in syncOnSync
    mapSyncer.syncMaps()
  File "C:\Users\10971\AppData\Roaming\Anki2\addons21\61346236\exportsync.py", line 26, in syncMaps
    self.getNotes2Sync()
  File "C:\Users\10971\AppData\Roaming\Anki2\addons21\61346236\exportsync.py", line 34, in getNotes2Sync
    xMid = xModelId(self.mw.col)
  File "C:\Users\10971\AppData\Roaming\Anki2\addons21\61346236\utils.py", line 117, in xModelId
    list(col.models.models.values())))[0]['id'])
<class 'IndexError'>: list index out of range

**Comment by CoffeeDrinkRabbit** [comment]
By toggle off SMR on another device, Anki's synchronization is temporarily successful

**Comment by Humorloos** [comment]
You are using the addon on two devices and you have the xmind file on one of the two devices but not on the other, right? That may cause an error when the addon looks for the file when trying to synchronize the map. At the moment there is no mechanism to throw an error if the file is not found. I will try to fix this now so we can see if the error still occurs.

**Comment by Humorloos** [comment]
I just tried to replicate your error but I failed to do so, just changing the file throws a different error when synchronizing. I just fixed that error but I'm not certain whether this also fixes the error that you got. It seems like the addon has problems finding the SMR model, have you tried updating the Addon?

**Comment by CoffeeDrinkRabbit** [comment]
Right now I'm at school. I created a map on my Mac and imported anki. Then I synced it to windows. Now it looks like everything has been synced successfully.

**Comment by Humorloos** [comment]
I would probably be able to find the error if you sent me your anki archives. You can find them by clicking *tools* -> *Add-ons* -> *View Files* (which is in the middle of the five buttons on bottom of the left side) -> and go up one directory and send me all files in this directory (in my case these are addons21, User 1, crash.log, gldriver, prefs21.db and README.txt) in a zip archive to l.loos95@gmail.

**Comment by CoffeeDrinkRabbit** [comment]
No problem, but do you mean the files of windows? 

Sorry, I just realized that I didn't update SMR on my windows when I tested the synchronization before, and then I updated it, and then the synchronization was smooth, which means that SMR on my Mac was the latest version when I ran into problems yesterday, but it didn't update to the latest version of SMR on windows.

Is it because the SMR versions are inconsistent that causes synchronization error?

**Comment by Humorloos** [comment]
It seems to me more like you had a corrupted version of the addon since this error should normally not occur at all but if it happens again try sending me the files that I mentioned earlier from the device where the error is occuring (would have been windows in this case), then I can check what the error is caused by.
